### ISSUE TITLE
dataset2 directory

### ISSUE THREAD

**Issue by MostofiSaba** [rabia174/COVID-19-Deep-Learning-CNN-Model#1]
Hello
I wanted to use your code as a practice but I can not find dataset2 folder!

**Comment by rabia174** [comment]
Hey! You can find the related dataset that I've used here in this link, https://github.com/rabia174/covid-chestxray-dataset, rename it as you like in your code.

**Comment by abdulraouf9567** [comment]
Hey , Can you please upload the exact dataset that you have used to train the model? not the above one please. The above one has only covid dataset not the normal dataset. Could you please provide it ?
